drop view  PRETTY_PURCHASE;
drop table YRB_BOOK;
drop table YRB_CATEGORY;
drop table YRB_CLUB;
drop table YRB_CUSTOMER;
drop table YRB_MEMBER;
drop table YRB_OFFER;
drop table YRB_PURCHASE;
drop table YRB_SHIPPING;
-- drop table NEW_SHIPPING;
-- drop table NEW_PURCHASE;
-- drop table NEW_CLUB;
-- drop table NEW_CATEGORY;
-- drop table NEW_OFFER;
-- drop table NEW_MEMBER;
